pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - apt-get update && apt-get install -y unzip
          - docker-php-ext-install pdo_mysql
          - curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php
          - composer install
          - cp .env.example .env
          - php artisan key:generate
          - php artisan migrate
          - php artisan db:seed
          - ./vendor/bin/phpunit
          - echo "Done!"
        services:
          - mysql
