name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          composer install

      - name: Configure environment
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan migrate
          php artisan db:seed

      - name: Run tests
        run: ./vendor/bin/phpunit

      - name: Done
        run: echo "Done!"

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: my_database
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s
