name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: pdo_mysql

    - name: Install dependencies
      run: |
        composer install

    - name: Generate environment file
      run: |
        cp .env.example .env
        php artisan key:generate

    - name: Run tests
      run: ./vendor/bin/phpunit

    - name: Deploy to EC2
      env:
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
          echo "${EC2_SSH_KEY}" > practice.pem
          chmod 600 practice.pem
          ssh -o StrictHostKeyChecking=no -i practice.pem ubuntu@${EC2_PUBLIC_IP} << 'EOF'
            cd /var/www/html/myApp
            
            
          EOF
        
